# Copyright 2023 DDS Permissions Manager Authors
---
micronaut:
  server:
    cors:
      enabled: true
      configurations:
        allowedOrigins:
          - 'http://localhost:3000'
---
micronaut:
  security:
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: pleaseChangeThisSecretForANewOne
              jws-algorithm: HS256
        generator:
          refresh-token:
            secret: pleaseChangeThisSecretForANewOneRefresh
    redirect:
      login-success: 'http://localhost:8080'
      login-failure: 'http://localhost:8080/failed-auth'
      logout: 'http://localhost:8080'
---
permissions-manager:
  application:
    passphrase:
      salt: "changeme"
  test:
    username: unity-admin
    email: unity-admin-test@test.test
    password: password
    is-admin: true
