micronaut:
  application:
    name: "Permissions Manager"
  server:
    cors:
      enabled: true
---
netty:
  default:
    allocator:
      max-order: 3
---
micronaut:
  server:
    cors:
      enabled: true
      configurations:
        allowedOrigins:
          - http://localhost:3000
  security:
    redirect:
      login-success: http://localhost:3000
      login-failure: http://localhost:3000
      logout: http://localhost:3000
    authentication: idtoken
    oauth2:
      clients:
        google:
          client-id: "887538804956-u62ckldg4a6e4elon7diken6pna3m2v5.apps.googleusercontent.com"
          client-secret: "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"
          openid:
            authorization:
              prompt: select_account
            issuer: "https://accounts.google.com"
    endpoints:
      logout:
        get-allowed: true
    intercept-url-map:
      - pattern: /favicon.ico
        http-method: GET
        access:
          - isAnonymous()
      - pattern: /
        http-method: GET
        access:
          - isAnonymous()
      - pattern: /login-failed.html
        http-method: GET
        access:
          - isAnonymous()
      - pattern: /assets/**
        http-method: GET
        access:
          - isAnonymous()
---
# hosted-domain:
#   url: 'test.test'
# ---
datasources:
  default:
    url: jdbc:h2:mem:devDb;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ""
    schema-generate: CREATE_DROP
    dialect: H2
jpa:
  default:
    entity-scan:
      packages: "io.unityfoundation.dds.permissions.manager"
    properties:
      hibernate:
        hbm2ddl:
          auto: update
