micronaut:
  application:
    name: 'Permissions Manager'
  router:
    static-resources:
      assets:
        paths: 'classpath:assets'
        mapping: '/assets/**'
---
netty:
  default:
    allocator:
      max-order: 3
---
micronaut:
  security:
    authentication: idtoken
    oauth2:
      clients:
        google:
          client-id: '689644842460-4s7vm9qddjbt8s03eac5ci1jmj8laebj.apps.googleusercontent.com'
          client-secret: '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'
          openid:
            authorization:
              prompt: select_account
            issuer: 'https://accounts.google.com'
    endpoints:
      logout:
        get-allowed: true
    intercept-url-map:
      - pattern: /favicon.ico
        http-method: GET
        access:
          - isAnonymous()
      - pattern: /
        http-method: GET
        access:
          - isAnonymous()
      - pattern: /login-failed.html
        http-method: GET
        access:
          - isAnonymous()
      - pattern: /assets/**
        http-method: GET
        access:
          - isAnonymous()
---
hosted-domain:
  url: 'test.test'
---
datasources:
  default:
    url: jdbc:h2:mem:devDb;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    schema-generate: CREATE_DROP
    dialect: H2
jpa:
  default:
    entity-scan:
      packages: 'io.unityfoundation.dds.permissions.manager'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
---
i18n:
  bundles:
    - applications
    - footer
    - groups
    - home
    - messages
    - navigation
    - topics
    - users
