---
dpm:
  bootstrap:
    data:
      enabled: true
      admin-users:
        - jeff@test.test
        - wilsonj@test.test
        - belloned@test.test
        - montesm@test.test
        - pasumarthis@test.test
        - unity-admin-test@test.test
      non-admin-users:
        - kstanley@test.test
        - jgracia@test.test
        - unity-test@test.test
      groups:
        -
          name: Alpha
          description: Alpha description
          users:
            -
             email: wilsonj@test.test
             admin-flags: [topic, application, group]
            -
              email: kstanley@test.test
              admin-flags: [group]
            -
              email: montesm@test.test
          topics:
            -
              name: Test Topic 123
              kind: B
              description: Topic 123 Description
            -
              name: Test Topic 456
              kind: B
          applications:
            -
              name: Application One
              description: Application One Description
            -
              name: Application Two
        -
          name: Beta
        -
          name: Gamma
        -
          name: Delta
