---
micronaut:
  server:
    cors:
      enabled: true
      configurations:
        allowedOrigins:
          - 'http://localhost:3000'
---
micronaut:
  security:
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: pleaseChangeThisSecretForANewOne
              jws-algorithm: HS256
        generator:
          refresh-token:
            secret: pleaseChangeThisSecretForANewOneRefresh
    redirect:
      login-success: 'http://localhost:3000'
      login-failure: 'http://localhost:3000/failed-auth'
      logout: 'http://localhost:3000'