name: Cypress Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Run the server with Gradle
        env:
          VITE_BACKEND_URL: /api
          MICRONAUT_ENVIRONMENTS: dev
        run: |
          ./gradlew app:run
      - name: Cypress run
        uses: cypress-io/github-action@v4
        # env:
        #   DEBUG: 'cypress:*'
        with:
          working-directory: ./frontend
          wait-on: 'http://localhost:8080'
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-videos
          path: frontend/cypress/videos/
